version: "3.1"
services:
  prlmntq_etl_twitter:
    build: .
    image: prlmntq_etl_twitter
    container_name: prlmntq_etl_twitter
    restart: always
    ports:
      - 8003:8003
    volumes:
      - .:/usr/src/etl_twitter
    networks:
      - prlmntq_net

networks:
  prlmntq_net:
    external: true
